### ISSUE TITLE
Faire 1 tableau au lieu de 2

### ISSUE THREAD

**Issue by tiphedor** [M-Garrigues/Maze_Generator#1]
ça fait des années qu'on en parle merde

**Comment by M-Garrigues** [comment]
Toujours pas.

**Comment by tiphedor** [comment]
Je trouve ça dommage que cette issue soit pas plus discutée, de grands experts se sont accorder à donner raison à mon hypothèse.

Le 7 nov. 2017 5:08 PM, Mathieu Garrigues <notifications@github.com> a écrit :

Toujours pas.

**Comment by M-Garrigues** [comment]
Ca fait un tableau au lieu de deux et ça veut aller à 42.

**Comment by tiphedor** [comment]
Norage de mon optimisage

Le 8 nov. 2017 09:58, Mathieu Garrigues <notifications@github.com> a écrit :

Ca fait deux tableaux au lieu d'un et ça veux aller à 42.
